/* 02_core_properties.c generated by valac 0.40.6, the Vala compiler
 * generated from 02_core_properties.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;
enum  {
	MAIN_0_PROPERTY,
	MAIN_COUNTER_PROPERTY,
	MAIN_NUM_PROPERTIES
};
static GParamSpec* main_properties[MAIN_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Main {
	GObject parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GObjectClass parent_class;
};

struct _MainPrivate {
	gint _counter;
};


static gpointer main_parent_class = NULL;

GType main_get_type (void) G_GNUC_CONST;
#define MAIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN, MainPrivate))
gboolean main_print_counter (Main* self);
gint main_get_counter (Main* self);
void main_set_counter (Main* self,
                       gint value);
void main_monitor_counter (Main* self);
Main* main_new (void);
Main* main_construct (GType object_type);
static gint main_main (gchar** args,
                int args_length1);
static GObject * main_constructor (GType type,
                            guint n_construct_properties,
                            GObjectConstructParam * construct_properties);
static gboolean _main_print_counter_gsource_func (gpointer self);
static void _main___lambda4_ (Main* self,
                       GParamSpec* obj);
static void __main___lambda4__g_object_notify (GObject* _sender,
                                        GParamSpec* pspec,
                                        gpointer self);
static void main_finalize (GObject * obj);
static void _vala_main_get_property (GObject * object,
                              guint property_id,
                              GValue * value,
                              GParamSpec * pspec);
static void _vala_main_set_property (GObject * object,
                              guint property_id,
                              const GValue * value,
                              GParamSpec * pspec);


gboolean
main_print_counter (Main* self)
{
	gboolean result = FALSE;
	FILE* _tmp0_;
	gint _tmp1_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = stdout;
	_tmp1_ = self->priv->_counter;
	main_set_counter (self, _tmp1_ + 1);
	fprintf (_tmp0_, "%d\n", _tmp1_);
	result = TRUE;
	return result;
}


void
main_monitor_counter (Main* self)
{
	FILE* _tmp0_;
	gint _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	_tmp1_ = self->priv->_counter;
	fprintf (_tmp0_, "Counter value has changed to %d\n", _tmp1_);
}


Main*
main_construct (GType object_type)
{
	Main * self = NULL;
	self = (Main*) g_object_new (object_type, NULL);
	return self;
}


Main*
main_new (void)
{
	return main_construct (TYPE_MAIN);
}


static gint
main_main (gchar** args,
           int args_length1)
{
	gint result = 0;
	Main* app = NULL;
	Main* _tmp0_;
	gtk_init (&args_length1, &args);
	_tmp0_ = main_new ();
	app = _tmp0_;
	gtk_main ();
	result = 0;
	_g_object_unref0 (app);
	return result;
}


int
main (int argc,
      char ** argv)
{
	return main_main (argv, argc);
}


gint
main_get_counter (Main* self)
{
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_counter;
	result = _tmp0_;
	return result;
}


void
main_set_counter (Main* self,
                  gint value)
{
	g_return_if_fail (self != NULL);
	if (main_get_counter (self) != value) {
		self->priv->_counter = value;
		g_object_notify_by_pspec ((GObject *) self, main_properties[MAIN_COUNTER_PROPERTY]);
	}
}


static gboolean
_main_print_counter_gsource_func (gpointer self)
{
	gboolean result;
	result = main_print_counter ((Main*) self);
	return result;
}


static void
_main___lambda4_ (Main* self,
                  GParamSpec* obj)
{
	g_return_if_fail (obj != NULL);
	main_monitor_counter (self);
}


static void
__main___lambda4__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self)
{
	_main___lambda4_ ((Main*) self, pspec);
}


static GObject *
main_constructor (GType type,
                  guint n_construct_properties,
                  GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	Main * self;
	parent_class = G_OBJECT_CLASS (main_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
	g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 1000, _main_print_counter_gsource_func, g_object_ref (self), g_object_unref);
	g_signal_connect_object ((GObject*) self, "notify::counter", (GCallback) __main___lambda4__g_object_notify, self, 0);
	return obj;
}


static void
main_class_init (MainClass * klass)
{
	main_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MainPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_main_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_main_set_property;
	G_OBJECT_CLASS (klass)->constructor = main_constructor;
	G_OBJECT_CLASS (klass)->finalize = main_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MAIN_COUNTER_PROPERTY, main_properties[MAIN_COUNTER_PROPERTY] = g_param_spec_int ("counter", "counter", "counter", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
}


static void
main_instance_init (Main * self)
{
	self->priv = MAIN_GET_PRIVATE (self);
	self->priv->_counter = 0;
}


static void
main_finalize (GObject * obj)
{
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
	G_OBJECT_CLASS (main_parent_class)->finalize (obj);
}


GType
main_get_type (void)
{
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (G_TYPE_OBJECT, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}


static void
_vala_main_get_property (GObject * object,
                         guint property_id,
                         GValue * value,
                         GParamSpec * pspec)
{
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_MAIN, Main);
	switch (property_id) {
		case MAIN_COUNTER_PROPERTY:
		g_value_set_int (value, main_get_counter (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void
_vala_main_set_property (GObject * object,
                         guint property_id,
                         const GValue * value,
                         GParamSpec * pspec)
{
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_MAIN, Main);
	switch (property_id) {
		case MAIN_COUNTER_PROPERTY:
		main_set_counter (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



