/* 02_core_properties.h generated by valac 0.40.6, the Vala compiler, do not modify */


#ifndef __02_CORE_PROPERTIES_H__
#define __02_CORE_PROPERTIES_H__

#include <glib.h>
#include <glib-object.h>

G_BEGIN_DECLS


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

struct _Main {
	GObject parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GObjectClass parent_class;
};


GType main_get_type (void) G_GNUC_CONST;
gboolean main_print_counter (Main* self);
void main_monitor_counter (Main* self);
Main* main_new (void);
Main* main_construct (GType object_type);
gint main_get_counter (Main* self);
void main_set_counter (Main* self,
                       gint value);


G_END_DECLS

#endif
